backend:
  name: git-gateway
  branch: main  # Your main GitHub branch

media_folder: "img/uploads"  # Where uploaded images go
public_folder: "/img/uploads"

collections:
  - name: "articles"
    label: "Articles"
    folder: "posts"  # All articles will be stored in /posts
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
